name: Build & Deploy

on:
  push:
    branches:
      - production

jobs:
  build-windows:
    name: Build Windows
    runs-on: windows-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup CMake
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: '3.28'

    - name: Setup Just
      uses: extractions/setup-just@v3
      with:
        github-token: ${{ secrets.MY_GITHUB_TOKEN }}

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup Build
      run: just setup

    - name: Build
      run: just build-release

    - name: Package
      run: just package

    - name: Zip Installer
      run: just zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: WindowsSetup
        path: ShootEm.zip

  release:
    name: Release
    needs: [build-windows]
    runs-on: ubuntu-latest
    permissions:
      contents: write # to be able to publish a GitHub release
      issues: write # to be able to comment on released issues
      pull-requests: write # to be able to comment on released pull requests
      # id-token: write # to enable use of OIDC for trusted publishing and npm provenance
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: WindowsSetup

      - name: Install
        run: npm install

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release
